server:
  port: 8080

spring:
  application:
    name: trimdb-server

  datasource:
    url: jdbc:postgresql://localhost:5432/trimdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: DEBUG
